version: 2,
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    assignees:
      - "Zac-Zajdel"
    labels:
      - "dependencies"